## Introduction
For this lesson, you are challenged to create your very own interactive videogame modeled after the board game [Battleship](https://en.wikipedia.org/wiki/Battleship_(game)). Click on the link and skim the Wikipedia article to familiarize yourself with the rules of the game.

## Creating functions
Functions are essential to any Python program. They allow us to simplify and shorten our program by encapsulating useful pieces of code so that we can reuse it throughout our program without rewriting the same code. You can think of it as a variable but instead of simply saving an object for later use, we are saving a process for later use.

A function is also different from plain code because it **only runs when it is called**. Run the cells below to see.

In [1]:
# Plain code
print('hi')

hi


In [2]:
# Function definition
def say_hi():
    print('hi')

In [3]:
# Calling a function
say_hi()

hi


### Anatomy of a function
Every function has 5 basic components:
1. **Name**: a short, descriptive name for the function which should be lowercase with words separated by underscores, e.g., `clear_board` for a function that removes all pieces from a game board


2. **Arguments**: the input of the function, or the information that the function needs to carry out its process. A function can have any number of arguments, even zero if no input information is needed.


3. **Comment**: a description of the function, its arguments, and its return values. This is technically not required for a function to work but it crucial for others to understand your code and helpful for you to outline your own code.


4. **Body**: the code inside a function that carries out the process.


5. **Return value**: the output of the function, or the finished product created by the function's process. Not every function needs to have a return value, e.g., `set_height` might change a value in an object but doesn't need to produce value whereas `get_height` which retrieves an object's height should return the height value. 

### How to write/define a function
In Python, we define a function using the `def` keyword, we enclose the arguments within parentheses, and return values at the end of the body code using the `return` keyword. The comment goes inside triple quotes beneath the function name and is formatted similar to what is shown below. Altogether, the format looks like this:


`def function_name(arg1, arg2):
    """Description of the the function
    Arguments:
        arg1 (arg1 data type) -- description of arg1
        arg2 (arg2 data type) -- description of arg2
    Returns: 
        return_val1(return_val1 data type) -- description of return_val1
        return_val2(return_val2 data type) -- description of return_val2
    """
    body code
    more body code
    return return_value1, return_value2`

### How to use the output of a function (return value)
A function's output can be used or saved in a variable by simply treating the function call as the return value.

In [4]:
def get_primes_under_10():
    return 1,2,3,5,7

In [5]:
print(get_primes_under_10())

(1, 2, 3, 5, 7)


In [6]:
numbers = get_primes_under_10()
print(numbers)

(1, 2, 3, 5, 7)


What type is the variable "numbers"? Do you remember the syntax? Try "print(type(numbers))"

In [7]:
#What type is the variable "numbers"?

print(type(numbers))

<class 'tuple'>


In [8]:
a, b, c, d, e = get_primes_under_10()
print(a)
print(d)

1
5


What types are the variables a, b, c, d, e?

In [9]:
#What types are the variables a, b, c, d, e?
print(type(a))

<class 'int'>


What did we learn? A function with multiple return values returns a tuple that contains each of the outputs! 

You can index a tuple like you would a string or a list.

In [10]:
print(numbers[0])
print(numbers[4])


1
7


#### Practice
Below is an example function, try reading it, figuring out what it does and then: 
1. Rename the function
2. Rename the function's arguments
3. Rename all variables used


to be more descriptive, so that you have an idea why that function/argument/variable exists just by reading its name.

In [11]:
def my_function(arg1):
    """
    This function is a mystery. REPLACE THIS WITH A DESCRIPTION.
    Arguments:
        arg1 (list of int) -- mystery (REPLACE)
    Returns:
        a (list of int) -- mystery (REPLACE)
        b (list of int) -- mystery (REPLACE)
    """
    a = []
    b = []
    
    for item in arg1:
        if item % 2 == 0:
            a.append(item)
        else:
            b.append(item)
            
    return a, b

In [12]:
### Play around with my_function here to help you figure out what it does

my_function([0, 1, 2, 4, 15])


([0, 2, 4], [1, 15])

In [13]:
### ANSWER

def split_even_odd(numbers):
    """
    From a list of integers, returns two separate lists containing the odd and even numbers 
    Arguments:
        numbers (list of int) -- the integers of interest
    Returns:
        evens (list of int) -- list of even numbers contained in argument
        odds (list of int) -- list of odd numbers contained in argument
    """
    evens = []
    odds = []
    
    for item in numbers:
        if item % 2 == 0:
            evens.append(item)
        else:
            odds.append(item)
            
    return evens, odds

### Function 1: Making the board
Battleship requires a game board (typically 10x10) and we will represent this by a 2D array. Below, you will complete the function `make_empty_board` to create a NxN array full of zeros, representing empty spaces.

In [14]:
import numpy as np

def make_empty_board(N):
    """Creates an empty NxN Battleship board
    Arguments:
        N (int) -- dimension of the square 2D array representing the Battleship board
    Returns:
        board (2D numpy array of ints) -- empty NxN board
    """
    # Insert code here
    
    board = np.zeros([N, N])
    
    return board 

In [15]:
### Test your make_board function here
my_board = make_empty_board(3)
print(my_board)

# add more tests as needed

print(type(my_board))


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


### Function 2: Placing Ships
At the beginning of a Battleship game, each player places ships on their board. You will create a function to create an empty board (by calling the `make_empty_board` function) and place M 1x1 ships (represented by 1s) on it randomly.

In [16]:
import numpy.random as random

def make_board(N, num_ships):
    """
    Creates an NxN Battleship board and randomly places the specified number of 1x1 ships 
    (represented by 1s) on it randomly.
    Arguments:
        N (int) -- size of board
        num_ships (int) -- number of ships to be randomly placed on the board
    Returns:
        ship_board (2D numpy array) -- the final board with placed ships (1 = ship)
    """
    # Insert code here
    # Hint: use random.randint(low, high) to generate a random integer from "low" up to but not
    #       including "high" -> random.randint(4,9) gives you either 4, 5, 6, 7, or 8.
    
    board = np.zeros([N, N])
    
    for ship in range(0, num_ships):
        x_coord = random.randint(0, N)
        y_coord = random.randint(0, N)
        
        # Hint: We wouldn't want to accidentally place a ship on top of another ship so make sure you 
        # put a piece of conditional code to check for that situation.
        
        while board[x_coord][y_coord] == 1:
            x_coord = random.randint(0, N)
            y_coord = random.randint(0, N)
        
        board[x_coord][y_coord] = 1
    
    return board

In [17]:
### Testing

make_board(3, 9)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Note: Having multiple boards
Since Battleship is a game of guessing, players can't be allowed to see the enemy's true board. This means we must have **2 separate boards per player**: one to store the opponent's actual ship locations (`true_board`), and one to store the player's knowledge of their opponent's board (`known_board`).

### Function 3: Attack
Tracking player's turns is fairly complicated so we will take care of that in the next lesson. For now, we will code another useful function that represents a single turn of one player. Each turn, a player attacks a single square on the opponents board, with the outcome either being a hit or a miss.

In [18]:
def attack(true_board, known_board, x, y):
    """
    Given the current combat situtation (encoded in true_board and known_board), strike the
    space with coordinates (x, y)). We represent a hit with +1 and a miss with -1.
    Arguments:
        true_board (2D numpy array) -- a board with the true location of ships (stays constant throughout a game)
        known_board (2D numpy array) -- a board that only indicates which ships have been hit (1 = hit, 0 = unknown, -1 = miss)
        x (int) -- x-coordinate of guess
        y (int) -- y-coordinate of guess
    Returns:
        new_known_board (2D array of ints) -- known_board that has been updated with the outcome
                                              of the attack.
    """
    # Check that (x, y) is on the board
    dimensions = true_board.shape
    if x in range(0, dimensions[0]) and y in range(0, dimensions[1]):
    
    # Check that (x, y) has not already been attacked
        if known_board[x][y] == 0:
    
    # Find out by looking at true_board if an attack at (x, y) will be a hit or a miss
            if true_board[x][y] == 1:
                print("Hit!")
    
    # Update known_board 
                known_board[x][y] = 1
            
            else:
                print("Miss!")
                known_board[x][y] = -1
                
        else:
            print("You've already attacked this space.")
   
    else:
        print("Your guess is off the board!")
        
    new_known_board = known_board
        
    return new_known_board

In [19]:
### Testing

true_board = make_board(3,3)
print(true_board)

known_board = make_empty_board(3)
print(known_board)

print(attack(true_board, known_board, 1, 1))


[[1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Hit!
[[0. 0. 0.]
 [0. 1. 0.]
 [0. 0. 0.]]


### Going Beyond
These functions are nice but Battleship isn't that fun if all the ships are the same size (1x1)! Your bonus challenge is to write a new `make_board` function that creates an official size Battleship board and places the correct number of correctly-sized ships (refer to the Wikipedia page) **according to user input**. 

**Tips**
1. Since this board is a 2D grid, you should ask the user for **3 pieces of information** when placing a ship for them: x-coordinate, y-coordinate, and orientation (vertical or horizontal).


2. To simplify placement of variably-sized ships in varying orientations (vertical and horizontal), you should use the uppermost, leftmost segment of the ship as the reference point for where it is placed on the board. For example, if a user asks to place a 3-long ship horizontally at (x=1, y=2), the ship will be placed at coordinates (1,2), (2,2), (3,2). This consistency makes it easier to check if the ship being placed will collide with other ships or fall off the board.


3. It is somewhat complicated to give the user a second chance if they place a ship in the wrong location so we will instead create an unforgiving program that simply throws away that ship if the user makes a mistake. >:)


4. Knowing some advanced looping keywords will be useful. Read this [article](https://www.digitalocean.com/community/tutorials/how-to-use-break-continue-and-pass-statements-when-working-with-loops-in-python-3) if you are unfamiliar with `break`, `continue`, and `pass`.

In [20]:
def make_true_board():
    """(FILL ME IN)
    Returns:
    (FILL ME IN)
    """
    # Create an empty board
    
    # Create list of ships (specifying their size)
    
    # Loop through ships
    
        # Show user the current board (print it)
    
        # Ask user for ship placement information (3 pieces of info) and store this information
    
        # Check that the placed ship doesn't collide with other ships
            # if it collides, tell the user and discard their ship (use a the keyword "continue")
            
        # Check that the placed ship doesn't fall off the board
            # if it falls off the board, tell the user and discard their ship (use a the keyword "continue")

        # Update the board
    
    return board

In [21]:
### Testing
