In [3]:
  # Here we import some packages that we need for the coding below, we only have 
# to import them once for the whole notebook so make sure to run this cell but
# there's no need to touch this code.

import numpy.random as random   # we need this module to generate random numbers 
                                # for placing ships randomly

import numpy as np  # we need this package to use numpy arrays as our 
                    # battleship board

## Introduction
For this lesson, you are challenged to create your very own interactive videogame modeled after the board game [Battleship](https://en.wikipedia.org/wiki/Battleship_(game)). Click on the link and skim the Wikipedia article to familiarize yourself with the rules of the game.

## Creating functions
Functions are essential to any Python program. They allow us to simplify and shorten our program by encapsulating useful pieces of code so that we can reuse it throughout our program without rewriting the same code. You can think of it as a variable but instead of simply saving an object for later use, we are saving a process for later use.

A function is also different from plain code because it **only runs when it is called**. Run the cells below to see.

In [4]:
# Plain code
print('hi')

hi


In [5]:
# Function definition
def say_hi():
    print('hi')

In [6]:
# Calling a function
say_hi()

hi


### Anatomy of a function
Every function has 5 basic components:
1. **Name**: a short, descriptive name for the function which should be lowercase with words separated by underscores, e.g., `clear_board` for a function that removes all pieces from a game board


2. **Arguments**: the input of the function, or the information that the function needs to carry out its process. A function can have any number of arguments, even zero if no input information is needed.


3. **Comment**: a description of the function, its arguments, and its return values. This is technically not required for a function to work but it crucial for others to understand your code and helpful for you to outline your own code.


4. **Body**: the code inside a function that carries out the process.


5. **Return value**: the output of the function, or the finished product created by the function's process. Not every function needs to have a return value, e.g., `set_height` might change a value in an object but doesn't need to produce value whereas `get_height` which retrieves an object's height should return the height value. 

### How to write/define a function
In Python, we define a function using the `def` keyword, we enclose the arguments within parentheses, and return values at the end of the body code using the `return` keyword. The comment goes inside triple quotes beneath the function name and is formatted similar to what is shown below. Altogether, the format looks like this:

In [7]:
def function_name(arg1, arg2):
    """Description of the the function
    Arguments:
        arg1 (arg1 data type) -- description of arg1
        arg2 (arg2 data type) -- description of arg2
    Returns: 
        return_val1(return_val1 data type) -- description of return_val1
        return_val2(return_val2 data type) -- description of return_val2
    """
    # body code goes here, e.g.,
    variable = arg1 + arg2
    return_value1 = variable
    return_value2 = -variable
    return return_value1, return_value2

### How to use the output of a function (return value)
A function's output can be used or saved in a variable by simply treating the function call as the return value.

In [8]:
def get_primes_under_10():
    return 1,2,3,5,7

In [9]:
print(get_primes_under_10())

(1, 2, 3, 5, 7)


In [10]:
numbers = get_primes_under_10()
print(numbers)

(1, 2, 3, 5, 7)


What type is the variable "numbers"? Do you remember the syntax? Try "print(type(numbers))"

In [11]:
#What type is the variable "numbers"?
print(type(numbers))


<class 'tuple'>


In [12]:
a, b, c, d, e = get_primes_under_10()
print(a)
print(d)

1
5


What types are the variables a, b, c, d, e?

In [13]:
#What types are the variables a, b, c, d, e?
print(type(a))

<class 'int'>


What did we learn? A function with multiple return values returns a tuple that contains each of the outputs! 

You can index a tuple like you would a string or a list.

In [14]:
print(numbers[0])
print(numbers[4])

1
7


#### Practice
Below is an example function, try reading it, figuring out what it does and then: 
1. rename the function...
2. rename the function's arguments...
3. rename all variables used...


...to be more descriptive, so that you have an idea why that function/argument/variable exists just by reading its name.

In [15]:
def my_function(arg1):
    """ This function is a mystery. REPLACE THIS WITH A DESCRIPTION.
    Arguments:
        arg1 (list of int) -- mystery (REPLACE)
    Returns:
        a (list of int) -- mystery (REPLACE)
        b (list of int) -- mystery (REPLACE)
    """
    a = []
    b = []
    
    for item in arg1:
        if item % 2 == 0:
            a.append(item)
        else:
            b.append(item)
            
    return a, b

### Now with more descriptive names ###

def split_even_odd(integers):
    """ Separates a list of integers into a list of evens and a list of odds
    Arguments:
        integers (list of int) -- list of numbers to be separated
    Returns:
        evens (list of int) -- even numbers from the provided list
        odds (list of int) -- odd numbers from the provided list
    """
    evens = []
    odds = []
    
    for integer in integers:
        if integer % 2 == 0:
            evens.append(integer)
        else:
            odds.append(integer)
            
    return evens, odds

In [16]:
### Play around with my_function here to help you figure out what it does
out=my_function([1, 2, 4, 5, 4, 3, 5])
print(out)

# Checking that our renamed version works as well
out=split_even_odd([1, 2, 4, 5, 4, 3, 5])
print(out)

([2, 4, 4], [1, 5, 3, 5])
([2, 4, 4], [1, 5, 3, 5])


### Function 1: Making the board
Battleship requires a game board (typically 10x10) and we will represent this by a 2D array. Below, you will complete the function `make_empty_board` to create a NxN array full of zeros, representing empty spaces.

In [17]:
def make_empty_board(N):
    """Creates an NxN Battleship board (NxN numpy array full of zeros)
    Arguments:
        N (int) -- dimension of the square 2D array representing the Battleship board
    Returns:
        board (2D numpy array of ints) -- empty NxN board (full of zeros) 
    """
    board = np.zeros((N,N), dtype=int)
    return board 

In [18]:
### Test your make_board function here
my_board = make_empty_board(3)
print(my_board)

# Try giving different arguments to the function (instead of 3)
# Count the height and width of the board to make sure it matches N (the argument)
my_board = make_empty_board(10)
print(my_board)


[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


### Function 2: Placing Ships
At the beginning of a Battleship game, each player places ships on their board. You will create a function that takes in a board, adds a 1x1 ship to the board in a random location. Keep in mind that locations on a board (2D array) are specified by 2 indices, much like (x,y) coordinates in a graph.

In [19]:

def place_ship(board):
    """
    Takes in a board, adds a single 1x1 ship (represented by a 1) in a random 
    location on the board, and then returns the updated board.
    Arguments:
        board (2D array of int) -- the game board before adding a ship
    Returns:
        board (2D array of int) -- the game board after adding a ship
    """
    # Create 2 random numbers between 0 and 9 and save them in variables x and y    
    # Hint: Use random.randint(low, high) to generate a random integer from "low" up to but not
    #       including "high"
    board_width = board.shape[0]
    x = random.randint(0, board_width)
    y = random.randint(0, board_width)
    
    # Reassign the spot in the board at the location (x,y) to be a 1
    # Hint: Recall that we can reassign a spot in a 2D list or array using
    # my_2d_array[1][2] = 23 
    # which assigns the value 23 to the spot in the 2nd column and 3rd row
    board[x][y]=1

    # Return the board now that we've updated it (already done for you below)
    return board


In [20]:
new_board = make_empty_board(2)

for i in range(10):
  new_board = place_ship(new_board)
  print(new_board)

[[0 0]
 [1 0]]
[[0 0]
 [1 0]]
[[0 0]
 [1 0]]
[[0 0]
 [1 1]]
[[0 0]
 [1 1]]
[[0 1]
 [1 1]]
[[0 1]
 [1 1]]
[[0 1]
 [1 1]]
[[0 1]
 [1 1]]
[[0 1]
 [1 1]]


### Function 3: Filling a board with ships
At the beginning of a Battleship game, each player places ships on their board. You will create a function to create an empty board (by calling the `make_empty_board` function) and place a specified number of 1x1 ships (represented by 1s) on it randomly.


In [21]:
def make_board(N, num_ships):
    """
    Creates an NxN Battleship board and randomly places the specified number of 1x1 ships 
    (represented by 1s) on it randomly.
    Arguments:
        N (int) -- size of board
        num_ships (int) -- number of ships to be randomly placed on the board
    Returns:
        ship_board (2D numpy array) -- the final board with placed ships (1 = ship)
    """
    # Create an empty board (by calling make_empty_board) and 
    # save it in a variable named board
    board = make_empty_board(N)

    # Create a for loop which loops 'num_ships' times
        # in each loop 
        # make a variable new_board which contains the output of place_ship(board)
        #   This variable new_board is just the original board but with another ship placed on it
        # Since we want to continue adding ships to the same board, reassign the variable board to the value of new_board (board = new_board)
    for ship in range(num_ships):
      new_board = place_ship(board)
        
        # Hint: We wouldn't want to accidentally place a ship on top of another ship so make sure you 
        # put a piece of conditional code to check for that situation.
      #while new_board.all() == board.all():
        #new_board = place_ship(board, N)

      board = new_board
    # Return the final board which is just board
    return board



In [22]:
### 
print(make_board(5, 4))

[[0 0 0 1 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]]


#### Note: Having multiple boards
Since Battleship is a game of guessing, players can't be allowed to see the enemy's true board. This means we must have **2 separate boards per player**: one to store the opponent's actual ship locations (`true_board`), and one to store the player's knowledge of their opponent's board (`known_board`).

### Function 4: Attack
Tracking player's turns is fairly complicated so we will take care of that in the next lesson. For now, we will code another useful function that represents a single turn of one player. Each turn, a player attacks a single square on the opponents board, with the outcome either being a hit or a miss.

In [23]:
def attack(true_board, known_board, x, y):
    """
    Given the current combat situtation (encoded in true_board and known_board), strike the
    space with coordinates (x, y)). We represent a hit with +1 and a miss with -1.
    Arguments:
        true_board (2D numpy array) -- a board with the true location of ships (stays constant throughout a game)
        known_board (2D numpy array) -- a board that only indicates which ships have been hit (1 = hit, 0 = unknown, -1 = miss)
        x (int) -- x-coordinate of guess
        y (int) -- y-coordinate of guess
    Returns:
        new_known_board (2D array of ints) -- known_board that has been updated with the outcome
                                              of the attack.
    """
    # In all cases below, print a message describing the outcome
    
    # Check that (x, y) is even on the board (not off the edge)
    if (x > np.shape(known_board)[0]) or (y > np.shape(known_board)[1]):
      print('That spot is off the board.')
      return known_board

    # Check the known_board to see if (x, y) has already been attacked
    if (known_board[x][y] == 1) or (known_board[x][y] == -1):
      print('You already attacked this spot.')
      return known_board

    # Find out by looking at true_board if an attack at (x, y) will be a hit or a miss
    if true_board[x][y] == 1:
      known_board[x][y] = 1
      print('Hit!')
    else:
      known_board[x][y] = -1
      print('Miss!')
      
    return known_board

In [24]:
### Testing
true_board = make_board(10,50)
print(true_board)

known_board = make_empty_board(10)
print(known_board)

print(attack(true_board, known_board, 1, 1))


[[0 0 1 1 1 0 1 0 1 0]
 [1 1 0 0 1 1 0 1 1 1]
 [0 0 0 1 0 0 0 1 0 0]
 [0 1 1 0 1 1 1 1 0 1]
 [1 0 0 0 1 0 0 1 0 0]
 [0 1 1 0 1 1 0 0 0 0]
 [0 0 0 1 1 1 0 1 0 1]
 [0 0 1 0 0 0 1 0 1 1]
 [1 1 0 1 1 0 0 0 1 1]
 [0 0 1 0 1 0 0 1 0 1]]
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Hit!
[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


### Going Beyond
These functions are nice but Battleship isn't that fun if all the ships are the same size (1x1)! Your bonus challenge is to write a new `make_board` function that creates an official size Battleship board and places the correct number of correctly-sized ships (refer to the Wikipedia page) with locations of those ships **chosen by the user**. 

**Tips**
1. Since this board is a 2D grid, you should ask the user for **3 pieces of information** when placing a ship for them: x-coordinate, y-coordinate, and orientation (vertical or horizontal).


2. To simplify placement of variably-sized ships in varying orientations (vertical and horizontal), you should use the uppermost, leftmost segment of the ship as the reference point for where it is placed on the board. For example, if a user asks to place a 3-long ship horizontally at (x=1, y=2), the ship will be placed at coordinates (1,2), (2,2), (3,2). This consistency makes it easier to check if the ship being placed will collide with other ships or fall off the board.


3. It is somewhat complicated to give the user a second chance if they place a ship in the wrong location so we will instead create an unforgiving program that simply throws away that ship if the user makes a mistake. >:)


4. Knowing some advanced looping keywords will be useful. Read this [article](https://www.digitalocean.com/community/tutorials/how-to-use-break-continue-and-pass-statements-when-working-with-loops-in-python-3) if you are unfamiliar with `break`, `continue`, and `pass`.

In [27]:
def make_true_board():
    """Creates a 10x10 Battleship board and places the 5 ships on it according to user input.
    Returns:
        board (2D numpy array of ints) -- the final board with placed ships (1 = ship)
    """

    # Create an empty board
    board = make_empty_board(10)
    
    # Create list of ships according to the Battleship rules
    ship_sizes = [5, 4, 3, 3, 2]
    ship_names = ['Carrier', 'Battleship', 'Cruiser', 'Submarine', 'Destroyer']
    
    # Loop through ship sizes
    for i in range(len(ship_sizes)):
        # Describe current ship to user
        print('\nPlacing a', ship_names[i], 'of size', ship_sizes[i], 'on the following board.\n')
    
        # Show user the current board (print it)
        print(board)
    
        # Ask user for ship placement information (3 pieces of info) and store this information
        x = int(input("Enter the x-coordinate for ship placement (number between 0 and 9): "))
        y = int(input("Enter the y-coordinate for ship placement (number between 0 and 9): "))
        orientation = input("Enter the orientation for ship placement ('v' for vertical or 'h' for horizontal): ")

        # Check that the placed ship doesn't fall off the board
            # if it falls of the board, print a message and continue without placing the ship (use the keyword "continue")
        if orientation[0].lower() == 'v':
            if x+ship_sizes[i] > 9 or x < 0:
                print('Ship placement invalid. Ship falls off board.')
                continue
        elif orientation[0].lower() == 'h':
            if y+ship_sizes[i] > 9 or y < 0:
                print('Ship placement invalid. Ship falls off board.')
                continue
        else:
            print('Invalid orientation input. Must start with "v", "h", "V", or "H".')
            continue

        # Check that the placed ship doesn't collide with other ships
        # First, add the ship to a temporary board
        temp_board = board.copy()
        if orientation[0].lower() == 'v':
            temp_board[x:x+ship_sizes[i], y] += 1
        elif orientation[0].lower() == 'h':
            temp_board[x, y:y+ship_sizes[i]] += 1
        else:
            print('Invalid orientation input. Must start with "v", "h", "V", or "H".')
            continue
        # Then, check if the temporary board has any collisions (i.e., any spots with a value > 1)
        if np.any(temp_board > 1):
            # if it collides, print a message and continue without placing the ship (use the keyword "continue")
            print('Ship placement invalid. Ships cannot overlap.')
            continue

        # Update the board
        board = temp_board
    
    return board

In [29]:
### Testing
make_true_board()

Placing a Carrier of size 5 on the following board.

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Ship placement invalid. Ship falls off board.
Placing a Battleship of size 4 on the following board.

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
Invalid orientation input. Must start with "v", "h", "V", or "H".
Placing a Cruiser of size 3 on the following board.

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


ValueError: invalid literal for int() with base 10: ''